version: '3.8'

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6380:6379"

  app:
    build: .
    depends_on:
      - redis
    ports:
      - "3000:3000"
    env_file:
      - .env.example
    volumes:
      - ./config/master.key:/rails/config/master.key:ro
      - .:/app
    command: ["rails", "server", "-b", "0.0.0.0"]

  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      - redis
      - app
    env_file:
      - .env.example
    volumes:
      - .:/app
volumes:
  pgdata:
